OPTIONS (SKIP=1)
LOAD data
INFILE 'C:\Users\harih\source\repos\RailwayWebApi\SQL LOADER\COACHES\Coaches.csv'
INTO TABLE COACHES
TRUNCATE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
COACHID,
TRAINID,
COACHPOSITION,
COACHNUMBER,
COACHTYPE,
TOTALSEATES  )

