OPTIONS (SKIP=1)
LOAD data
INFILE 'C:\Users\harih\source\repos\RailwayWebApi\SQL LOADER\Seates\Seates.csv'
INTO TABLE SEATES
TRUNCATE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
SEATID,
COACHTYPE,
SEATNUMBER,
BEARTH  )

