OPTIONS (SKIP=1)
LOAD data
INFILE 'C:\Users\harih\source\repos\RailwayWebApi\SQL LOADER\TEMP_ROUTES_DISTANCE_1.csv'
INTO TABLE TEMP_TRAINROUTES
TRUNCATE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
Train_Number,
TRAINID,
STATIONID,
Stn_Name,
Distance )

