OPTIONS (SKIP=1)
LOAD data
INFILE 'C:\Users\harih\source\repos\RailwayWebApi\SQL LOADER\TRAINROUTES\export.csv'
INTO TABLE TRAINROUTES
TRUNCATE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
ROUTEID,
TRAINID,
STATIONID,
STATIONORDER,
SCHEDULEARRIVAL DATE "HH24:MI",
SCHEDULEDEPARTURE DATE "HH24:MI",
PLATFORMNUMBER,
DAY  )

