OPTIONS (SKIP=1)
LOAD data
INFILE 'C:\Users\harih\source\repos\RailwayWebApi\SQL LOADER\TRAINDETILS\Train_Details.csv'
INTO TABLE TRAINS
TRUNCATE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
TRAINID,
TRAIN_NAME,
TRAINNUMBER,
SOURCESTATIONID,
SOURCESTATIONNAME,
DESTNATIONSTATIONID,
DESTNATIONSTATIONNAME,
TOTALDISTANCE,
TRAIN_TYPE  )

